### ISSUE TITLE
Support several licences

### ISSUE THREAD

**Issue by Ge0** [vivienm/template-python#3]
I'd like to add the MIT licence among the choices. How should I proceed?

I thought about creating a `licences/` directory at the root and putting every possible licences files then copy the right one into the generated project, but I'd like to have yout opinion on what's the best way to do things.

**Comment by vivienm** [comment]
@Ge0 I think the easiest solution is to have all licenses in the template file `LICENSE.txt`, as done here: https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/LICENSE. It could get messy if we want to support many licenses, but that's not the case for now.

You'll also need to

* Add the new license option `mit` to `cookiecutter.json`.
* Add the corresponding `__license__` definition to the template's `__init__.py`.
* Add the corresponding [classifier](https://pypi.python.org/pypi?%3Aaction=list_classifiers) to the template's `setup.py`.

**Comment by vivienm** [comment]
Done (311ce204d9a4f38015dbe2ae41f499802985768a).
