### ISSUE TITLE
Exclude build directory from flake8 check

### ISSUE THREAD

**Issue by Ge0** [vivienm/template-python#4]
```
(acapela_group) ge0@pryen ~/git/Ge0/acapela-group ±master⚡ » tox -e flake8
GLOB sdist-make: /home/ge0/git/Ge0/acapela-group/setup.py
flake8 create: /home/ge0/git/Ge0/acapela-group/.tox/flake8
flake8 installdeps: flake8
flake8 installed: flake8==3.5.0,mccabe==0.6.1,pycodestyle==2.3.1,pyflakes==1.6.0
flake8 runtests: PYTHONHASHSEED='2731710858'
flake8 runtests: commands[0] | flake8
./build/lib/acapela_group/base.py:30:5: E303 too many blank lines (2)
./build/lib/acapela_group/base.py:33:1: W293 blank line contains whitespace
./build/lib/acapela_group/base.py:40:5: E303 too many blank lines (2)
```

Happened because I previously ran `python setup.py install` somehow.

Would be nice to only check src/module and tests/ by default. Not anything else.

**Comment by vivienm** [comment]
> Would be nice to only check src/module and tests/ by default. Not anything else.

@Ge0 I'd prefer to check *everything* by default, and blacklist some files when needed. Otherwise, it's really easy to miss a file worth checking, e.g. `setup.py`.

I'm not sure about blacklisting `build/lib` either. IIRC it contains your app's code, so the test should pass, right? (And if it's a deprecated version, it's better to remove it anyway.)

**Comment by Ge0** [comment]
> @Ge0 I'd prefer to check everything by default, and blacklist some files when needed. Otherwise, it's really easy to miss a file worth checking, e.g. setup.py.

Did not think about it. Good catch.

> I'm not sure about blacklisting build/lib either. IIRC it contains your app's code, so the test should pass, right? (And if it's a deprecated version, it's better to remove it anyway.)

Sure. it's just that when I fix my source code without launching setup.py again, I get errors from flake8 since my `build/`files are not updated. That's it.
